"""Language-independent domain enumerations shared by engines, services and schemas."""
from enum import Enum


class StrEnum(str, Enum):
    def __str__(self) -> str:  # pragma: no cover
        return str(self.value)


class JourneyState(StrEnum):
    POLICY_ACTIVE = "POLICY_ACTIVE"
    INCIDENT_DETECTED = "INCIDENT_DETECTED"
    CLAIM_STARTED = "CLAIM_STARTED"
    DOCUMENT_COLLECTION = "DOCUMENT_COLLECTION"
    READINESS_CHECK = "READINESS_CHECK"
    SUBMISSION = "SUBMISSION"
    UNDER_REVIEW = "UNDER_REVIEW"
    QUERY_RAISED = "QUERY_RAISED"
    QUERY_RESOLUTION = "QUERY_RESOLUTION"
    CLAIM_RESOLUTION = "CLAIM_RESOLUTION"
    RESOLVED = "RESOLVED"
    ESCALATED = "ESCALATED"


class JourneyHealth(StrEnum):
    HEALTHY = "HEALTHY"
    ATTENTION = "ATTENTION"
    BLOCKED = "BLOCKED"
    ESCALATED = "ESCALATED"
    COMPLETE = "COMPLETE"


class InsurerClaimStatus(StrEnum):
    """External (mock insurer) claim states. Deterministic."""
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    DOCUMENT_PENDING = "DOCUMENT_PENDING"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SETTLED = "SETTLED"


class SettlementStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"


class PaymentStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"


class ClaimType(StrEnum):
    CASHLESS = "CASHLESS"
    REIMBURSEMENT = "REIMBURSEMENT"
    OWN_DAMAGE = "OWN_DAMAGE"
    THIRD_PARTY = "THIRD_PARTY"
    GADGET = "GADGET"


class PolicyType(StrEnum):
    HEALTH = "HEALTH"
    MOTOR = "MOTOR"
    GADGET = "GADGET"


class DocumentType(StrEnum):
    POLICY_COPY = "policy_copy"
    ID_PROOF = "id_proof"
    CLAIM_FORM = "claim_form"
    HOSPITAL_BILL = "hospital_bill"
    DISCHARGE_SUMMARY = "discharge_summary"
    MEDICAL_CERTIFICATE = "medical_certificate"
    PRESCRIPTION = "prescription"
    DIAGNOSTIC_REPORT = "diagnostic_report"
    DRIVING_LICENSE = "driving_license"
    RC_COPY = "rc_copy"
    FIR_COPY = "fir_copy"
    REPAIR_ESTIMATE = "repair_estimate"
    DAMAGE_PHOTOS = "damage_photos"
    PURCHASE_INVOICE = "purchase_invoice"
    OTHER = "other"


class RequirementStatus(StrEnum):
    MISSING = "MISSING"
    UPLOADED = "UPLOADED"
    VALIDATED = "VALIDATED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    SUBMITTED = "SUBMITTED"


class RequirementSource(StrEnum):
    POLICY = "POLICY"
    INCIDENT = "INCIDENT"
    CLAIM_TYPE = "CLAIM_TYPE"
    INSURER_QUERY = "INSURER_QUERY"


class DocValidation(StrEnum):
    VALID = "VALID"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    INVALID = "INVALID"
    PENDING = "PENDING"


class ActionType(StrEnum):
    SUBMIT_CLAIM = "SUBMIT_CLAIM"
    ATTACH_DOCUMENT = "ATTACH_DOCUMENT"
    RESUBMIT_CLAIM = "RESUBMIT_CLAIM"
    ATTACH_AND_RESUBMIT = "ATTACH_AND_RESUBMIT"
    POLL_STATUS = "POLL_STATUS"
    REQUEST_DOCUMENT_FROM_USER = "REQUEST_DOCUMENT_FROM_USER"
    NOTIFY_USER = "NOTIFY_USER"
    CONFIRM_DOCUMENT_VALUE = "CONFIRM_DOCUMENT_VALUE"
    RAISE_FOLLOW_UP = "RAISE_FOLLOW_UP"
    RESOLVE_EXTERNAL_CONFLICT = "RESOLVE_EXTERNAL_CONFLICT"
    MODIFY_DOCUMENT = "MODIFY_DOCUMENT"
    ESCALATE = "ESCALATE"


class GateDecision(StrEnum):
    SAFE = "SAFE"
    CONFIRM = "CONFIRM"
    ESCALATE = "ESCALATE"
    DENY = "DENY"


class RiskClass(StrEnum):
    AUTO_RECOVERABLE = "AUTO_RECOVERABLE"
    USER_CONFIRMATION_REQUIRED = "USER_CONFIRMATION_REQUIRED"
    HUMAN_ESCALATION_REQUIRED = "HUMAN_ESCALATION_REQUIRED"


class ActionStatus(StrEnum):
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    DENIED = "DENIED"
    ESCALATED = "ESCALATED"


class RecoveryStatus(StrEnum):
    PLANNED = "PLANNED"
    AWAITING_USER = "AWAITING_USER"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"


class Blocker(StrEnum):
    NONE = "none"
    MISSING_REQUESTED_DOCUMENT = "missing_requested_document"
    REQUESTED_DOCUMENT_NOT_ATTACHED = "requested_document_not_attached"
    MISSING_REQUIRED_DOCUMENTS = "missing_required_documents"
    DOCUMENT_INCONSISTENCY = "document_inconsistency"
    CONFLICTING_EXTERNAL_STATE = "conflicting_external_state"
    INSURER_DELAY = "insurer_delay"
    READY_TO_SUBMIT = "ready_to_submit"
    AWAITING_INSURER = "awaiting_insurer"
    ESCALATED = "escalated"
    RESOLVED = "resolved"
    UNSUPPORTED_STATE = "unsupported_state"


class Actor(StrEnum):
    USER = "USER"
    SYSTEM = "SYSTEM"
    AI = "AI"
    INSURER = "INSURER"
    N8N = "N8N"
    HUMAN_AGENT = "HUMAN_AGENT"


class AuditAction(StrEnum):
    USER_LOGGED_IN = "USER_LOGGED_IN"
    POLICY_UPLOADED = "POLICY_UPLOADED"
    POLICY_INDEXED = "POLICY_INDEXED"
    POLICY_QUESTION_ANSWERED = "POLICY_QUESTION_ANSWERED"
    INCIDENT_ANALYZED = "INCIDENT_ANALYZED"
    CLAIM_CREATED = "CLAIM_CREATED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_VALIDATED = "DOCUMENT_VALIDATED"
    READINESS_COMPUTED = "READINESS_COMPUTED"
    CLAIM_SUBMITTED = "CLAIM_SUBMITTED"
    INSURER_QUERY_RECEIVED = "INSURER_QUERY_RECEIVED"
    USER_REQUESTED_RECOVERY = "USER_REQUESTED_RECOVERY"
    AI_IDENTIFIED_BLOCKER = "AI_IDENTIFIED_BLOCKER"
    RECOVERY_PLAN_CREATED = "RECOVERY_PLAN_CREATED"
    ACTION_PROPOSED = "ACTION_PROPOSED"
    ACTION_GATE_APPROVED = "ACTION_GATE_APPROVED"
    ACTION_GATE_DENIED = "ACTION_GATE_DENIED"
    ACTION_GATE_ESCALATED = "ACTION_GATE_ESCALATED"
    USER_CONFIRMED = "USER_CONFIRMED"
    N8N_EXECUTED = "N8N_EXECUTED"
    N8N_FALLBACK_EXECUTED = "N8N_FALLBACK_EXECUTED"
    EXTERNAL_STATE_CHECKED = "EXTERNAL_STATE_CHECKED"
    RECOVERY_VERIFIED = "RECOVERY_VERIFIED"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    JOURNEY_UPDATED = "JOURNEY_UPDATED"
    ESCALATION_CREATED = "ESCALATION_CREATED"
    USER_CONFIRMED_DOCUMENT_VALUE = "USER_CONFIRMED_DOCUMENT_VALUE"
    DEMO_LOADED = "DEMO_LOADED"


class NotificationKind(StrEnum):
    INFO = "INFO"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    SUCCESS = "SUCCESS"
    WARNING = "WARNING"


class Language(StrEnum):
    EN = "en"
    HI = "hi"
    MR = "mr"


SARVAM_LANGUAGE_CODES = {"en": "en-IN", "hi": "hi-IN", "mr": "mr-IN"}
